version: "3.8"
services:
  restaurant-review-postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: "restaurant-review"
      POSTGRES_PASSWORD: "r3s4ur4ntr3v13w"
    ports:
      - "5432:5432"

  restaurant-review-redis:
    image: redis:7.4.2-alpine
    command: redis-server
    ports:
      - 6379:6379

  restaurant-review-rabbitmq:
    image: "rabbitmq:4.0.5-management-alpine"
    ports:
      - 5672:5672
      - 15672:15672
