spring:
  application:
    name: restaurant-review
  datasource:
    password: r3s4ur4ntr3v13w
    url: jdbc:postgresql://localhost:5432/restaurant-review
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
app:
  allowed:
    origin: http://localhost:4200
